#!/bin/sh -x

TEMPLATES=/home/stack/templates
STACK_NAME=overcloud
mkdir -p ./logs
LOG_FILE=./logs/overcloud-deploy-${STACK_NAME}.$(date +%s).log

# openstack overcloud deploy \
time openstack overcloud deploy --templates ${TEMPLATES}/openstack-tripleo-heat-templates \
--stack ${STACK_NAME} \
--timeout 180 \
-e ${TEMPLATES}/containers-default-parameters.yaml \
-e ${TEMPLATES}/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
-e ${TEMPLATES}/node-info.yaml \
-e ${TEMPLATES}/network-environment.yaml \
-e ${TEMPLATES}/firstboot.yaml \
-e ${TEMPLATES}/containers-prepare-parameter.yaml \
-e /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml \
--ntp-server 192.168.4.1 2>&1 | tee $LOG_FILE
#--templates ./openstack-tripleo-heat-templates \
#-e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \

#-e ${TEMPLATES}/fencing.yaml \
#-e ${TEMPLATES}/post-config-environment.yaml \
ln -sf $LOG_FILE ./overcloud-deploy.log 
