heat_template_version: 2014-10-16

description: >
  Change root password

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties: 
      parts:
        - config: {get_resource: root_password}

  root_password:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/bash
        echo changeme | sudo passwd root --stdin

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
  
