description: 'Default Deployment plan

  '
environments:
- path: overcloud-resource-registry-puppet.yaml
- path: environments/docker-ha.yaml
- path: environments/containers-default-parameters.yaml
name: overcloud
parameter_defaults:
  RootStackName: overcloud
passwords:
  AdminPassword: yJ6CyCt6aMqRpPFoE0GQNxYQX
  AdminToken: SQSmZWQshX38Aw1WW2ZOL9FBQ
  AodhPassword: Ik0SrGPuNpLtnrEGYplUEWYVP
  BarbicanPassword: VlYXqPPDuJ8yIFdRc9QH7t63H
  BarbicanSimpleCryptoKek: NCanfkRemDV-j6-gj899qe9Mw3yE5iblKUSIOoo-Paw=
  CeilometerMeteringSecret: RX88PNJYq3hX42Dd3njnIogD3
  CeilometerPassword: dS3Z0UviR4Q9X89c0lJAmuj15
  CephAdminKey: AQBkBpVeAAAAABAApqJ7ynn2gByIgxBFVZifcA==
  CephClientKey: AQBkBpVeAAAAABAAIynf8Jo502EnMOpiWyoLvw==
  CephClusterFSID: 7b547086-7de8-11ea-aef5-52540061adcc
  CephDashboardAdminPassword: AQBkBpVeAAAAABAA9300xkvwbAFJn1ihe4+c1g==
  CephGrafanaAdminPassword: AQBkBpVeAAAAABAA8oYxLA33exmZDIphRCzAiw==
  CephManilaClientKey: AQBkBpVeAAAAABAAGYXVnm/V7hqCPor3/0rySg==
  CephMdsKey: AQBkBpVeAAAAABAAzybnG5jufj3/WFRgXV16kw==
  CephMonKey: AQBkBpVeAAAAABAA7idn0cpnN87TP0J3XuxS9w==
  CephRgwKey: AQBkBpVeAAAAABAAB+rgH1XLhuRgL44BsJCGYg==
  CinderPassword: cQrnI84hxgtLbvbQoC5CV71Vw
  CongressPassword: qoa4tjEq9hUoj7g5eNm7h8VgE
  DesignatePassword: y67JjxvLqmSTFyc2TlnpB7Aar
  DesignateRndcKey: qFQQrLuDqqyf6zun2LSbU2Bp6RlY5OJ3ef7JEEn1gcA=
  Ec2ApiPassword: lm6dgctB4XuhxahfoFTmXD7jB
  EtcdInitialClusterToken: vqN6tRXmQBEPB8EqvdsD1GxCZ
  GlancePassword: Gu0pxFzV3VxtYDUWhYxkEuuuL
  GnocchiPassword: m1XsFzfpkvtF0nvgnv1VZkw4x
  HAProxyStatsPassword: HQXKkJCOYnKH7gusBDeRWOTw4
  HeatAuthEncryptionKey: 1QmVA0lfmds1ueC8MHYTmieAs1rJJxWg
  HeatPassword: yalDUx8rYFQg5j2rPybbVVqUq
  HeatStackDomainAdminPassword: gBXP915incrqBsZnOIMRt2rEr
  HorizonSecret: jYmOtMbuwt
  IronicPassword: C7hJHSVy53qaMUApS7EmUqZNh
  KeystoneCredential0: _2opc38ysWSNjblngrL5hyjOoghOCKSoTIp2RmtqWGY=
  KeystoneCredential1: apxG9JzWD0fVDjogxiouYAMs9rOoQLq09Y_tsJqi3gs=
  KeystoneFernetKey0: GA-E7KCgWAZR3h3oBVSZWUyqPzTXHvXNaoNRFemOXpM=
  KeystoneFernetKey1: UxE3AxWF72ncJbBm0iOIAEkzYpprwpxVcsIeGq7qRKg=
  KeystoneFernetKeys:
    /etc/keystone/fernet-keys/0:
      content: hx9jRVvsaOQ1yz4oAVwgD_8ERiHMF4uycVnLi8u2bfk=
    /etc/keystone/fernet-keys/1:
      content: kKV6AxsnjPKWtBwRSOQTAfpkGnTG7xnz8oRWULSZcs0=
  LibvirtTLSPassword: tMX6MsqkKhAJfqZxCZAJ0vWg0
  ManilaPassword: yvLZc9cFd5Cvse0UXUf9aYqfF
  MigrationSshKey:
    private_key: '-----BEGIN RSA PRIVATE KEY-----

      MIIEogIBAAKCAQEAmMfdHQNYE2iPFosnvWz9Wq7h1gnVhoiVTOgma1G2eNfZSUb+

      kWnkGuiZNRKyYXugGR0a0hYnjgGtqpffxPOBnA0ojalcPreCl4E9w4DKvmOOyJQg

      ggg02u8HYRtuxrbVVxwxESEvLqDow4SZTNT+Gu9qsGPLH39D65msy535toLbxbqe

      6THhylaDWQlrmLoOOYG9sb2agEJf803iK33S3H0fUivfYRURPXKC/E8x53u28n9T

      ZDLubPUTThIJlAo1/+v7RMcwljrcaFxCCgAn3Rf/eTUeDVDb5gTklIjB6ct+tNu+

      IMD5rH3Hnequ8OC+O1hFPxUl3X65JDaTmOsWxQIDAQABAoIBACcD4xNlpzhNmzzG

      jH9zNb/SqRlfqYeRmY7qOeVuGIsDlBmCZ7/6qqW0gGttOuBqEZhYNmEwByncg9zs

      q9g/1vli4thKR6Q8eLz35C3o1d2Izw2pxiNutRCzuc6ykrdsOU7lhCI7tzDRJp/H

      XN6iBcIbIcOpuFVyyoV/2QCmdv6ER1NohLuBqzodWqoGVECqyeQJa8TC6EqkFVu7

      l8M1s/ri0SxiGBq4a7UZFxwqwGjePiWNGr5yYg9DlnOu8k4Uq59GMnduQpe3kUWX

      fzssG+FCqLpDDMyYnUXA/BVvgk3sKYj62upVGPSpEUsn6z7w7r5Pfq1YkDxYEbFh

      RliWHAECgYEAygbfmiYYNavwBMUean9C0TPLtszU6irv7TqJbRpIxwzpyLxELUqL

      PLxhvBfb7NXrdRNvPF/LYOkZRZ/dzNqhEUmN80ybm1pmJTtpaEoTv4pqRihBD8XH

      tCXpsb8uDwBVmkGO7SeEkT+qDB8UD3SjUHjXqhnM1miQy1ELiGQWgi0CgYEAwZjs

      RU/5Q28Ir2nOo/2UciY2B6f9DCYkb8mj2miea37zlQHJR23nOSGK9gwR6jbI7hyQ

      0dLEDrattFxgsEmzpCmc5zXVhnUwmdmaLiUSuV9tcuCucOpzd4+sjBDk3BFgfFs/

      imiX5B1/8IozSECU1kawnxwdwyUEOwTOKx3g/fkCgYBZic5UTYnxT7DjDFI8tQZy

      Hditvf6ngjwwEf+SgVG8FrcOppI42I75biyK5rAsOWtPyjtEsNg8rVLsDryI7GTy

      en0VVeCpa9lVqw0+kYZLIBeV3IVpbijiaOM4ShkpwOYvpdqotRkGHwdItAV6DCHN

      qqE63JByfomd8t9/pYxsSQKBgEyRbuD7AFrrT0QRVOkHIe8DrdrZVfu4GjEcTvHS

      7tUVIMGOM01M6mZuHceyfmNjx5RlN+HEukYXehwbbSJMBACpdKT9ZbYII3C134Tg

      pMcsNt14f4WpNIHVESlUhS+Er+R/MmJLe8d841z/S8kHwdX9n11OgXbs7P9qpx/m

      cVYBAoGAZRPY3IXUfspY+ZCxsBm2B1yLUr/h1YxyCC94bgWmSeoUNUn9biNjwdn1

      l8gCzYkQx9o26RPTQUpjE8MkLomWdppQUPm/+NSYWOpOkX8dBCF+liwdSvBTunpP

      HvRQZUvTnTPgtnPQdX8C0PnWapbSJwrFbacrSgOdS+aSgzOGWE0=

      -----END RSA PRIVATE KEY-----

      '
    public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYx90dA1gTaI8Wiye9bP1aruHWCdWGiJVM6CZrUbZ419lJRv6RaeQa6Jk1ErJhe6AZHRrSFieOAa2ql9/E84GcDSiNqVw+t4KXgT3DgMq+Y47IlCCCCDTa7wdhG27GttVXHDERIS8uoOjDhJlM1P4a72qwY8sff0PrmazLnfm2gtvFup7pMeHKVoNZCWuYug45gb2xvZqAQl/zTeIrfdLcfR9SK99hFRE9coL8TzHne7byf1NkMu5s9RNOEgmUCjX/6/tExzCWOtxoXEIKACfdF/95NR4NUNvmBOSUiMHpy360274gwPmsfced6q7w4L47WEU/FSXdfrkkNpOY6xbF
      Generated by TripleO
  MistralPassword: omuh54hMWEcELE21D4YYAOYyM
  MysqlClustercheckPassword: Y3h8EflYkMupjKjfl55kI8gZB
  MysqlRootPassword: Mcdz8VoUpJ
  NeutronMetadataProxySharedSecret: lsnJIKrEdzk7Iex4U3ToeGNWB
  NeutronPassword: 4HZNNLQGD4ssS7mXsJdMX8yiX
  NotifyPassword: 5Ws2IHkZPyEZMId2YYApZb6Ez
  NovaPassword: zmteiLHQH7sa4BbMranSNEANV
  NovajoinPassword: aW7WuweYdojNhyn9DuW7VAa6K
  OctaviaCaKeyPassphrase: soeN34oAAnxiR0DQxQHvvMfrj
  OctaviaHeartbeatKey: WG75kAeIcSa3i0RjTq42DxI3R
  OctaviaPassword: LCbej8GgPzPmZU0ZtT0pHsNZi
  OctaviaServerCertsKeyPassphrase: Jxb2b3U9HHrfEkZm3BEQiryTnA2z37wN
  OpenDaylightPassword: hgijGaTv23K9ou2ODapxYxHFh
  PacemakerRemoteAuthkey: 3sgrnm3cZsQwJLTvDTlU7GWkdjKwKAnraMumDKbTnssUU7pfWABJLtMi4modGfUS5EMlc2RuYOdRDyB3AZWKHZP81vbvn6PVWhODVUQC0oHpsU4cTkaIEqeBoet0618EcQGRckhkKG4jz5PvElguG4cMxle3iLvfmuBv5o3E15rB8zyiIbiA5xer82BHGckUm4mU5T0Wjlbul4pNijmt78AtJgbTuD0E51ubQkltQGmzcetb60ceZTvspXlUUKExMiA3i5fVtjIfMSznkBqNCSTF69mvbNez5ythYsEpnUW2RB9lYuz8hYHdnFZQLDKAZ2Wcqcz520i9D3wikXLYXM45xYib354PpIJAH03kuhBoLQHtNRCNmWbRNc3Z6mj598O9WylIIPP8ghheenjckM2PzugXWN9kl4sp7uODIGgSFVvN63CKVcBVhARbt63glTi5mqx4Pa1JFOkf03BdiXfm0P0laf0ZEhgODhPM60dkcnZqtptDfi2t8bm2KsJpCYoX11s3sCNXp0Qgpk5tMJ1NooCfVSi35JnWqcezS0u0kczS552xQJSoiVPAgsWDwxsa2EDcUsPBnSdosP0RPCFZmaOhLiECk4mRHWZWy50obSpTa2cWEf4RfUnmMnZ6aLWxlrWEoLMPa9rgvs0kg1JAM88CY0d8CPayGNldgDDE6vY5TTaynsKjayoScoPV9il3SxdXO5bMhOa66pVal8xUOVzl0ff6WR3GXlS2SPkTsCjBaRF6jnKmXgNPF0SyPIQLSWwSIkImuXTq49kZu2D4HLv5D0lxpvnTydVQxXg3j5qM61ppKgW12XkYw1bgd5DYZ1IBhRBNH5R4qB2iYU4Ujgcxc14QkoR5H0kD9VKjwopAPANDgslp3V1Vj3OHzwUNejxe85ZjS74PGT2B7O0kMgEsVlXVXRGCgJjJBXTZfutXSHTG37OLTy17wiKkSUhI7VTUz8bEUdUzhAuI6Ok29E9dX1cCzURPvPxcI6Eq2PYM64rSn0LEjzkBXWIoO8CB3qos6Cq17wkXucxob9yUKTNCKbm9wXR6lfItGmoXpgiryVjlLx1vzlBIZvw9PsLmJXpdVhZPRLNWndkRmdXriRAbHMS84t0M8irCflgsjYJEn6JChgzHdLGckrns7TQNHSYEuk22qhTNnpEyYzNn8EzmLu9B0jYQwOr6FlQrLxzN2aT76pzaQ9XdQVfKW53wQT7CnnZ4jWUUUDmvyv6uWHfLmxodotNuQ4vufbkYwMp0YZXvwhcVFbT3oXIXTtqdUIpEAj6EIdho2VZkQjyeFrWJujGoBf8x5NKWqGg6GJkz8n2ToBCqPKq89z4JEaapKaFkwF1wLPar7T4HsqN8qAFxuNEWROayeCmipLtFttXwUD55BxyakDGkRUJbUx2Hr8tatzH8WrZDw3egEaDXiL7X7qz7Mh8FRFBo8yLK3Oe3FYfyzc927jEneNMwzSUpQnN3C26qpeeA6WoZBOigPiJQR0d2c8Gn8Jvo4HJs5Dsz4OAcystKGwxWfAe8Th86SMInI1LVfkG3WPB7SA62Cjk2VLLIS6cS7VGVXV7i1Z0xA33IxowjKNc5MlJEo8Myppy4BcwRwzdd0iZNsAP5SxnQHLzk3yAwWDJT1x0vdZV8AZ62HCcicdbYKW5PrRREfL94rN8htsZ3gyesyo3m8H6GCxbTqYBxn2rPtOujJ2sJdMMYQbexwXqgDZkCR3kLBJKya61W2S5PfKu8vq8jqmkDeRK9cZtXt4K8CrhNnGSyozOuX8n7ZmMcCnALrxMhjNanJOTd5MqE3KwQY6Ici4l9TjM7duGh0ygC6X4rbhnL0XS146G2lkfWhNS6Ff2DIKxiwBT2ELiVGP9v4ILmPAVpH1JYwSBopcsx2pFWuxhA91FT9EF3pkta4d4xCIBe6muD9lTZH31fSmQdGozJUJHLLdARyMKWm2nLRTXTypWXfwvLjLv1ynI3VSXp8KNMVpYMkNWCCab1YmhcPtJZS0pJsre5LIfe6XQS4Z2vaGXBnT4m0tKswLfssMLPEZuUh6mvFVF3t7dkEo0TlFxKymjYzZfrJVLCilfUCxPaJDYvGPX3XYOnVMDh6tPuDa2T8pu77q3B4W7Q3WU0kbUI8arzyaRC7Idl82hn9Q4glr6toQRGNGOcgpZ72Z8nonGnNfStqsUhBKQYyNyVnOKspTudgRP4xjKbCPxiC9QfsXAwrFz2IkI3ghB9pRtKyFFwMlzhIOHNoPAZ4v29bQQniO6PF4NyobOMiXVPBB2BrHFoZlOG7KzPusVfFtIe7gkgZXArifwv1Cw2NHxAhMXCwDTtYNW1OFVwvwtfMxEjEI3uOpwgipWCm12KfLGVHeYz8olPa2WSykLuT1UWS4yAsB2O6jbW3nuyJTwdZEETTR08EL1kdKCTxKXU5QZ8euQsNBNXcyJ92Rg5VXoGUGAWPKmDmt7E2ZeluMLpIn0zzkWxUXMai2KMwYllC1OqloYiEPja91ZmLzTVnrLIwyAGLJSLA9AP0RZL9wOvfOKZuizRGbXMRcrmNdP0xuYTUX48ZOJf1s7zfXZZU6lZXkQquOcaF89OXBsVdaNpByof1wtZQhA02iDDu42el6w5qZJ4SxsiD2v3FZ8KwXOhmWviWRLJvEissABphqSQvAyUaBXOfZIb8ZjJdXoLkmZbVAVbW9UZLPSpWl5PfOsPxNTotvkGerZvCXRqVG2MDXXdLoktNHzUIXfFCRJOAKfmO0MdAJzd4hJChQdhIwRu15RyhnHkUMYqai96FRcewiAKrRvDt0xkARCtmG2ywZwZp6tN2ytKv2mR10MwH8hXjbljTPEziv83wlWypEdBx1PEBlccnmlV4yFN3It3lENUqa5gRFc8UbboUdO8kfwgLynymDPhRksvIw9CPFxBexSNmgpsDx511ciV9t46fyfCt1U3XrL65qONYPjBN8Lcn8joLGTERgz1i8D2l1wxo8z0kkzFzycIJj1ahr6NPBSyqCJthDy5ccAspVlo7IG4tDdMahEBDOJWek4f9tOHXXLXBJAob2aDOtc6DakLhtCbqS8DG9dVxkxchHIjy79u0lve1DW3gGnlX68JFbBMZO34tSgobyOUYEUzrw1UDU5AOxGM8Taw4UgULnXhVFB0I4pp9bv8oeJ5qy0gHnG4msBvatb2ispKWM9PKdLzWuUChqOdlteq19Y4DMFrrCMk1vOMBMvTIdprGsD4SJbifRulU3ZMID1bYh3zXtFEFxLrhdMQNo8xpoRd9B2B3wYJkFq36IaHDQzQu7BwgJYSQDW8r8Xji3ztdaXg2T3HXrvXMYCHXaJFjaqc3Vj1wMGpf7TwqAG15etSIuPyjtWYeN8qUyQ4DEpRqXW5q9phFuqRyN75pRB7vLIoql8zX4yO2tj02Sxh0V5EgaY57HIIDCLixeXzGeXU2Gd8JvJqQwekKMsdzpdL0KoXGxxk659mwjZPMqudar8rAHMGH47JJTkSAB65YnpMYZI9SL13fv2dR4InwwERIPPdvvZCmAQLo1KdZzjSIGBW0T6y8iQX1AmhnL8xOfTxMzjfvhTedevD2Ma1m7vaqx3qQEqqTALIzKgfCKNhp0F5kGRSODFObIMaCMOqBTtzEJXOtyFJEpTe1lESARKPczxuEgS4jXPM0fpygdxrOY7urMSz90yFNJmb6QeMhocRaBqMyTO4jlXXnnGCWkJ1ypoecAj1jR3MMQvqfmfrPuTJC48jvQEVzh2VICYsEXAjSF44q9QOkyBORw0vQwYr78a7EZVnmGWnH9DrQsgxsZL38CPmlAOlg0KeyAAgFpCz0VQEKBJvd8vJNPfhiJFUXHzSTJ4mTK9TP1CFFBaKU84BDqbPaMIQqefccTISw1KlxRN4MovEQpkMnrfA0ecKLkBxduqSp4JmeEVhCUf6L15Yn0qTTakRCrqc31RlK0PiCkNrlgyn4FfJCNQKbiUtR3PCleWnJMcAa8I44xSyAsP4UzqPpFuzL5hv1qHRwkebjKxw61Iz5Vo82GDVmE1ydyO6Bs165oMKhvbPEulKT3uLV41j4d9wEA3xIjcZenGKC2KYThk6zUG2
  PankoPassword: 4Y4uoC58uj9751WqutWij1R3p
  PcsdPassword: Tmoz6tioa641w5nJ
  PlacementPassword: h1vA0iveJAPRL7hB3LLgswtak
  RabbitCookie: 9YVGIVuOGPkearsTX4X1
  RabbitPassword: qkNkdeDEb5afoKZ5vci7muk8G
  RedisPassword: WKewM9Xne0qGMouNEnJD9vFVH
  RpcPassword: ph7zzjeUEfCJ1FeUXtw7xf5of
  SaharaPassword: SPADPLxRIugqKVNulDOxiLgvT
  SnmpdReadonlyUserPassword: vUt6bxydkocV8xdNlCCvMJvRf
  SwiftHashSuffix: UiNGmjsfj04xvOm9WQEgUUiMA
  SwiftPassword: aWgKcEwToJovmXoi9RbOZ6KNM
  ZaqarPassword: YA7rzIlnzu89Ct7UEcmBcheRa
template: overcloud.yaml
version: 1.0
